# Generated by Django 2.2.15 on 2020-08-23 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200823_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='investors',
            field=models.ManyToManyField(blank=True, related_name='investing_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
