# Generated by Django 2.2.15 on 2020-08-23 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200823_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producing_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
