# Generated by Django 2.2.15 on 2020-08-24 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200824_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='project',
        ),
    ]
