# Generated by Django 2.2.15 on 2020-08-24 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_investment_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='app.Project'),
            preserve_default=False,
        ),
    ]
