# Generated by Django 2.2.15 on 2020-08-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_investment_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default='location', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='topic',
            field=models.CharField(default='topic', max_length=255),
            preserve_default=False,
        ),
    ]
